name: Build LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Установить TeX Live
        uses: xu-cheng/latex-action@v2

      - name: Скомпилировать PDF
        run: |
          latexmk -pdf -silent main.tex
